package com.net.core.network.model

import kotlinx.serialization.Serializable

@Serializable
data class TeamData(
    var idTeam: String? = null,
    var idSoccerXML: String? = null,
    var idAPIfootball: String? = null,
    var intLoved: String? = null,
    var strTeam: String? = null,
    var strTeamShort: String? = null,
    var strAlternate: String? = null,
    var intFormedYear: String? = null,
    var strSport: String? = null,
    var strLeague: String? = null,
    var idLeague: String? = null,
    var strLeague2: String? = null,
    var idLeague2: String? = null,
    var strLeague3: String? = null,
    var idLeague3: String? = null,
    var strLeague4: String? = null,
    var idLeague4: String? = null,
    var strLeague5: String? = null,
    var idLeague5: String? = null,
    var strLeague6: String? = null,
    var idLeague6: String? = null,
    var strLeague7: String? = null,
    var idLeague7: String? = null,
    var strDivision: String? = null,
    var strStadium: String? = null,
    var strKeywords: String? = null,
    var strRSS: String? = null,
    var strStadiumThumb: String? = null,
    var strStadiumDescription: String? = null,
    var strStadiumLocation: String? = null,
    var intStadiumCapacity: String? = null,
    var strWebsite: String? = null,
    var strFacebook: String? = null,
    var strTwitter: String? = null,
    var strInstagram: String? = null,
    var strDescriptionEN: String? = null,
    var strDescriptionDE: String? = null,
    var strDescriptionFR: String? = null,
    var strDescriptionCN: String? = null,
    var strDescriptionIT: String? = null,
    var strDescriptionJP: String? = null,
    var strDescriptionRU: String? = null,
    var strDescriptionES: String? = null,
    var strDescriptionPT: String? = null,
    var strDescriptionSE: String? = null,
    var strDescriptionNL: String? = null,
    var strDescriptionHU: String? = null,
    var strDescriptionNO: String? = null,
    var strDescriptionIL: String? = null,
    var strDescriptionPL: String? = null,
    var strKitColour1: String? = null,
    var strKitColour2: String? = null,
    var strKitColour3: String? = null,
    var strGender: String? = null,
    var strCountry: String? = null,
    var strTeamBadge: String? = null,
    var strTeamJersey: String? = null,
    var strTeamLogo: String? = null,
    var strTeamFanart1: String? = null,
    var strTeamFanart2: String? = null,
    var strTeamFanart3: String? = null,
    var strTeamFanart4: String? = null,
    var strTeamBanner: String? = null,
    var strYoutube: String? = null,
    var strLocked: String? = null
)