#!/usr/bin/env bash
printf "\e[33;1m%s\e[0m\n" 'Running the check formatter'
./gradlew spotlessApply
if [ $? -ne 0 ]; then
  printf "\e[31;1m%s\e[0m\n" 'Running the check format error'
exit 1
printf "\e[33;1m%s\e[0m\n" 'Finished running the check formatter'
fi
